version: '3.8'

services:
  mlflow-server:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_server:/mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
    command: >
      bash -c "pip install mlflow==2.9.2 &&
      echo 'Waiting for MLflow server to start...' &&
      sleep 15 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --default-artifact-root file:/mlflow/artifacts
      --backend-store-uri sqlite:////mlflow/mlflow.db"

  training:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/healthcheck || exit 0"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      mlflow-server:
        condition: service_healthy
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./training:/app/training